#%RAML 1.0
title: Win API
version: 1.0.0
baseUri: https://admin.apoyos.win/api/v1/
protocols: HTTPS
traits:
    standardErrors:
        responses:
            404:
                body:
                    application/json:
                        type: string
                        example: |
                            'Not Found'
            500:
                body:
                    application/json:
                        type: object
                        properties:
                            exception: string
                            message: string
types:
    Answer:
        type: object
        properties:
            id: integer
            created_at: datetime
            option_id: integer
            question_id: integer
            response_time: integer
            specification: boolean
            subject_id: integer
            survey_id: integer
            updated_at: datetime
            aids: Aid[]
    Question:
        type: object
        properties:
            id: integer
            formulation: string
            needs_specification: boolean
            specification: string
            dimension_id: integer
            category_id: integer
            options: Option[]
    Option:
        type: object
        properties:
            id: integer
            type:
                enum: [ 'yes', 'no' ]
            label: string
            order: integer
            value: integer
            question_id: integer
    Aid:
        type: object
        properties:
            id: integer
            label: string
    Specification:
        type: object
        properties:
            id: string
            label: string
    Survey:
        type: object
        properties:
            id: integer
            subject_id: integer
            event_id: integer
            script_id: integer
            hash: string
            is_completed: boolean
            last_answer_at?: datetime
            deleted_at?: datetime
            created_at: datetime
            updated_at: datetime
            onboarding:
                type: array
            questionnaire:
                type: object
                properties:
                    name: string
                    id: integer
                    description: integer
                    questions: Question[]
            aids: Aid[]
            specifications: Specification[]
    Event:
        type: object
        properties:
            id: integer
            label: string
            starts_at: datetime
            ends_at: datetime
            status:
                enum: ['active', 'inactive']
            hash: string
            deleted_at?: datetime
            created_by: integer
            created_at: datetime
            updated_at: datetime
    Subject:
        type: object
        properties:
            id: integer
            personal_id: string
            given_name: string
            family_name: string
            sex:
                enum: ['female', 'male', 'other']
            consent_at: datetime
            works: boolean
            studies: boolean
            studies_at: string
            last_connection_at: string
            deleted_at?: string
            created_at: string
            updated_at: string
    Result:
        type: object
        properties:
            dimensions:
                type: ResultDimension[]
    ResultDimension:
        type: object
        properties:
            id: integer
            label:
                type: string
                description: Nombre de la dimensión
            values:
                type: integer[]
                description: Puntaje obtenido en cada pregunta de esta dimensión
            score:
                type: integer
                description: Puntaje total de la dimensión obtenido por el usuario
            max:
                type: integer
                description: Puntaje máximo que un usuario puede obtener en la dimensión
            min:
                type: integer
                description: Puntaje mínimo que un usuario puede obtener en la dimensión
            answered:
                type: integer
                description: Cantidad de preguntas que el usuario contestó en la dimensión
            level:
                enum: ['low', 'medium', 'high']
                description: Nivel logrado por el usuario en la dimensión
/answers:
    displayName: Respuestas
    post:
        description: Enviar la respuesta a una pregunta
        body:
            multipart/form-data:
            application/json:
                properties:
                    question_id:
                        required: true
                        description: ID de la pregunta
                        type: integer
                    subject_id:
                        required: true
                        type: integer
                        description: ID del sujeto
                    survey_id:
                        required: true
                        type: integer
                        description: ID de la aplicación
                    hash:
                        required: true
                        type: string
                        description: Hash de la aplicación (survey)
                    option_id:
                        required: true
                        type: integer
                        description: ID de la opción seleccionada
                    response_time:
                        required: true
                        type: integer
                        description: Tiempo de respuesta del usuario, en segundo
                    aids:
                        required: false
                        type: array
                        items: integer
                        description: IDs de "ayudas" (aids) cuando la respuesta es "sí, con apoyo"
                    specification:
                        required: false
                        type: array
                        items:
                            enum: ['home', 'outside']
                        description: Especificación de lugar para la pregunta. Valores permitidos: 'home', 'outside'
        responses:
            201:
                description: Se ha añadido una nueva respuesta del sujeto
                body:
                    application/json:
                        type: Answer
            200:
                description: Se ha editado una respuesta del sujeto
                body:
                    application/json:
                        type: Answer
/events:
    displayName: Eventos de aplicación
    /{hash}:
        get:
            description: Obtener información sobre un evento de aplicación
            is: [ standardErrors ]
            uriParameters:
                hash:
                    description: Hash del evento
                    type: string
                    required: true
            responses:
                200:
                    body:
                        application/json:
                            type: Event
/surveys:
    displayName: Aplicación de la encuesta
    /{id}:
        get:
            description: Obtener información de una aplicación
            is: [ standardErrors ]
            uriParameters:
                id:
                    description: ID de la aplicación
                    type: integer
                    required: true
            queryParameters:
                hash:
                    description: Idenitificador de la aplicación (survey)
                    type: string
                    required: true
            responses:
                200:
                    body:
                        application/json:
                            type: Survey
    /results:
        get:
            description: Obtener los resultados de la aplicación del cuestionario
            queryParameters:
                hash:
                    description: Identificador de la aplicación (survey). Requerido si no se usa la cabecera X-WIN-SURVEY-HASH
                    type: string
            headers:
                X-WIN-SURVEY-HASH:
                    description: Identificador de la aplicación (survey)
                    type: string
            responses:
                200:
                    body:
                        application/json:
                            type: Result
    post:
        description: Crear una nueva aplicación
        body:
            multipart/form-data:
            application/json:
                properties:
                    subject_id:
                        type: integer
                        required: true
                    script_id:
                        type: integer
                        required: false
                        default: 1
        responses:
            200:
                body:
                    application/json:
                        type: Survey
/subjects:
    displayName: Usuario de la encuesta
    post:
        description: Crear un usuario
        body:
            multipart/form-data:
            application/json:
                properties:
                    personal_id:
                        description: RUT o DNI
                        type: string
                        required: false
                    given_name:
                        description: Primer nombre
                        type: string
                        required: false
                    family_name:
                        description: Apellido
                        type: string
                        required: false
                    sex?:
                        description: Sexo del sujeto
                        enum: ['female', 'male', 'other']
                    consent_at:
                        description: Debe indicar la fecha en que el sujeto dio su consentimiento para recopilar sus datos
                        type: datetime
                        required: true
                    works?: boolean
                    studies?: boolean
                    studies_at?: string
                    works_at?: string
                    birthday:
                        description: Fecha de nacimiento, en formato YYYY-MM-DD
                        type: date
        responses:
            201:
                description: Sujeto creado correctamente
                body:
                    application/json:
                        type: Subject
            422:
                description: Error de validación al intentar creación de sujeto
                body:
                    application/json:
                        example: |
                            {
                                "errors": {
                                    "sex": [
                                        "The selected sex is invalid"
                                    ],
                                    "studies": [
                                        "The studies field must be true or false"
                                    ]
                                },
                                "message": "The given data was invalid"
                            }